# Standard Sobol analysis
# Note: if you want to run the code for a replication check, all the output results should be the same as
#       the example outputs except for the computational time (because the machines are different). 
#       This note applies to all the scripts in this study.

# Remove all existing environment and plots
rm(list = ls())
graphics.off()
source("0_library.R")

# Define the test model in each dimension and perform the Sobol analysis
for (k in 1:6){
  # d dimensional model
  set.seed(k)
  d <- D[k]

  # Folder for d dimension test scenario under the working directory
  # "Data" is the folder that saves all the relevant parameters during the tests
  folder <- paste(folderpath,d,"D",sep="")
  if (Testmodel_ind==2){
    folder <- paste(folderpath,"Hymod",sep="") 
  }
  if (Testmodel_ind==3){
    folder <- paste(folderpath,"SacSma",sep="") 
  }
  if (!dir.exists(folder)){
    dir.create(paste(folder,"/Sobol",sep=""), recursive = TRUE)
  }
  
  # For each considered sample size, perform the Sobol analysis
  for (m in 1:length(tot_size)){
    
    # "sensobol" package has a special design for a sobol matrix used for the analysis,
    #     N here is the length of the matrix.
    # The relationship between N and the sample size (when calculating up to 2nd order indices) is:
    #     sample size = N*(d+2+d*(d-1)/2)
    # Note we take the nearest integer, hence the actual sample size is an approximation of the list of sample
    #     size we consider. 
    N <- floor(tot_size[m]/(d+2+d*(d-1)/2))
    
    # if N < 2, increase size directly
    if (N >= 2){
      print(tot_size[m])
      # Input matrix and output. The input matrix is generated by the Sobol sequence algorithm.
      mat <- sobol_matrices(N = N, params = as.character(c(1:d)), order = "second")
      
      # For 2 hydro models, need to change the input ranges accordingly
      if (Testmodel_ind >=2){
        mat <- Mapping(mat,Range)
      }
      X <- split(t(mat), rep(1:dim(mat)[1], each = d))
      
      # Model total evaluation time
      start.time<-Sys.time()
      Y <- sapply(X, Testmodel)
      end.time<-Sys.time()
      
      # Model average evaluation time
      avg_eval_time <- difftime(end.time,start.time,units = "secs")/length(Y)
      
      # Sensitivity analysis time
      start.time<-Sys.time()
      S <- sobol_indices_boot(Y=Y,N=N,params = as.character(c(1:d)),
                              boot=TRUE,R=100,order="second")
      end.time<-Sys.time()
      T_Sobol<-difftime(end.time,start.time,units = "secs")
      
      # convergence of ranking:
      #  
      Sens <- S$boot$t[ ,c((1+d):(2*d))]
      Rank <- t(apply(Sens, 1, rank))
      for (boot_ind1 in 1:99){
        T <- boot_ind1
        for (boot_ind2 in (T+1):100){
          Rho <- rep(NA,d)
          Weights <- rep(NA,d)
          for (para_ind in 1:d){
            Weights[para_ind] <- (max(Sens[boot_ind1,para_ind],max(Sens[boot_ind2,para_ind])))^2
          }
          Weights_sum <- sum(Weights)
          for (para_ind in 1:d){
             Rho[para_ind] <- abs(Rank[boot_ind1,para_ind]-Rank[boot_ind2,para_ind])*
               Weights[para_ind]/Weights_sum
          }
          if (boot_ind2 == 2){
            Rho_all <- Rho
          } else{
            Rho_all <- append(Rho_all,Rho)
          }
        }
      }
      Rho_all <- matrix(Rho_all, nrow = d)
      Rho_all <- apply(Rho_all, 2, sum)
      if (!any(is.na(Rho_all))){
        #print(quantile(Rho_all,probs = 0.95, na.rm = TRUE))
        if (quantile(Rho_all,probs = 0.95, na.rm = TRUE) < 1){
          save(avg_eval_time,file = paste(folder,"/avg_eval_time",sep=""))
          save(S,file = paste(folder,"/Sobol/S_Sobol",sep=""))
          save(T_Sobol,file = paste(folder,"/Sobol/T_Sobol",sep=""))
          break
        }
      }
      
    }
  }
}

# Finally, save the convergence size of each model dimension into a vector
if (Testmodel_ind == 1){
  Sobol_convergesize <- rep(NA,length(D))
  for (i in 1:length(D)) {
    folder <- paste(folderpath,D[i],"D/Sobol",sep="")
    load(paste(folder,"/S_Sobol",sep=""))
    Sobol_convergesize[i] <- S$C
  }
  #For G function, save the convergence size of all six dimensions as a whole file
  save(Sobol_convergesize,file = paste(folderpath,"Sobol_convergencesize",sep=""))
}
if (Testmodel_ind >= 2){
  load(paste(folder,"/Sobol/S_Sobol",sep=""))
  Sobol_convergesize <- S$C
  save(Sobol_convergesize,file = paste(folder,"/Sobol_convergencesize",sep=""))
}

